name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'

      - name: Cache packages
        id: python-packages-cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ github.job }}-packages-${{ hashFiles(format('{0}/{1}', github.workspace, 'requirements.lock')) }}-${{ hashFiles(format('{0}/{1}', github.workspace, 'requirements-dev.lock')) }}

      - name: Install dependencies
        run: pip install -r requirements.lock -r requirements-dev.lock
        if: steps.python-packages-cache.outputs.cache-hit != 'true'

      - name: Lint
        run: flake8 src

      - name: Test
        run: pytest
